In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("../dataset/raw/IMDb_movies_india.csv", encoding='latin1')
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [3]:
df.isnull().sum()

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [4]:
df = df.drop(columns=['Name'])

In [5]:
# removing rows without rating
df = df.dropna(subset=['Rating'])
print(df.shape)

(7919, 9)

In [6]:
df['Year'].head()

1    (2019)
3    (2019)
5    (1997)
6    (2005)
8    (2012)
Name: Year, dtype: str

In [7]:
# formating the way year is written
df['Year'] = df['Year'].str.extract(r'(\d{4})')
df['Year'] = pd.to_numeric(df['Year'], errors = 'coerce')
df['Year'].head()

1    2019
3    2019
5    1997
6    2005
8    2012
Name: Year, dtype: int64

In [8]:
# Force the column to a string type first, then strip the parentheses
df['Year'] = df['Year'].astype(str).str.strip('()')

# Convert it safely back to a number
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df['Year'].head()

1    2019
3    2019
5    1997
6    2005
8    2012
Name: Year, dtype: int64

In [9]:
# cleaning duration column
df['Duration'] = df['Duration'].astype(str).str.extract(r'(\d+)')
df['Duration'] = pd.to_numeric(df['Duration'], errors = 'coerce')
df['Duration'].head()

1    109.0
3    110.0
5    147.0
6    142.0
8     82.0
Name: Duration, dtype: float64

In [10]:
# cleaning votes column
df['Votes'] = df['Votes'].astype(str).str.replace(
    ',',
    '',
    regex = False
)
df['Votes'] = pd.to_numeric(df['Votes'], errors = 'coerce')
df['Votes'].head()

1       8
3      35
5     827
6    1086
8     326
Name: Votes, dtype: int64

In [11]:
# filling missing values - numerical
df['Year'] = df['Year'].fillna(
    df['Year'].median(),
    inplace = True
)

df['Duration'] = df['Duration'].fillna(
    df['Duration'].median(),
    inplace = True
)

df['Votes'] = df['Votes'].fillna(
    df['Votes'].median(),
    inplace=True
)
df.head()

C:\Users\samit\AppData\Local\Temp\ipykernel_12100\2931764065.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Year'] = df['Year'].fillna(
C:\Users\samit\AppData\Local\Temp\ipykernel_12100\2931764065.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Duration'] = df['Duration'].fillna(
C:\Users\samit\AppData\Local\Temp\ipykernel_12100\2931764065.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Votes'] = df['Votes'].fillna(

,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,2019,109.0,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,2019,110.0,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,1997,147.0,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,2005,142.0,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,2012,82.0,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia

In [12]:
# filling missing values - Categorical
# genre, director, actor 1,2,3,
df['Genre'] = df['Genre'].fillna(
    'Unknown',
    inplace=True
)
df['Director'] = df['Director'].fillna(
    'Unknown',
    inplace=True
)

df['Actor 1'] = df['Actor 1'].fillna(
    'Unknown',
    inplace=True
)

df['Actor 2'] = df['Actor 2'].fillna(
    'Unknown',
    inplace=True
)

df['Actor 3'] = df['Actor 3'].fillna(
    'Unknown',
    inplace=True
)

C:\Users\samit\AppData\Local\Temp\ipykernel_12100\2099460054.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Genre'] = df['Genre'].fillna(
C:\Users\samit\AppData\Local\Temp\ipykernel_12100\2099460054.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Director'] = df['Director'].fillna(
C:\Users\samit\AppData\Local\Temp\ipykernel_12100\2099460054.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Actor 1'] = df['Actor 1'].fillna(
C:\Users\samit\AppData\Local\Temp\ipykernel_12100\2099460054.py:17: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Actor 2'] = df['Actor 2'].fillna(
C:\Users\samit\AppData\Local\Temp\ipykernel_12100\2099460054.py:22: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Actor 3'] = df['Actor 3'].fillna(

In [13]:
df.isnull().sum()

Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [14]:
df.nunique()

Year          92
Duration     178
Genre        433
Rating        84
Votes       2033
Director    3140
Actor 1     2552
Actor 2     2874
Actor 3     3065
dtype: int64

In [15]:
# encoding categorical columns to intergers
genre_encoder = LabelEncoder()

df['Genre'] = genre_encoder.fit_transform(
    df['Genre']
)
df['Genre']

1        268
3        207
5        177
6        331
8        367
        ...
15501     28
15503     28
15504      0
15505     38
15508     38
Name: Genre, Length: 7919, dtype: int64

In [16]:
#director
director_encoder = LabelEncoder()

df['Director'] = director_encoder.fit_transform(
    df['Director']
)
df['Director']

1         811
3        1749
5        2005
6        2643
8         174
         ...
15501     500
15503    2339
15504    1418
15505    1338
15508    1171
Name: Director, Length: 7919, dtype: int64

In [17]:
# actor 1
actor1_encoder = LabelEncoder()

df['Actor 1'] = director_encoder.fit_transform(
    df['Actor 1']
)
df['Actor 1']

1        1782
3        1589
5         508
6         931
8        2521
         ...
15501     631
15503     550
15504    1405
15505     145
15508     631
Name: Actor 1, Length: 7919, dtype: int64

In [18]:
# actor 2
actor2_encoder = LabelEncoder()

df['Actor 2'] = director_encoder.fit_transform(
    df['Actor 2']
)
df['Actor 2']

1        2815
3         890
5          85
6        1388
8        1461
         ...
15501    1436
15503     936
15504    2536
15505    2670
15508     934
Name: Actor 2, Length: 7919, dtype: int64

In [19]:
# actor 3
actor3_encoder = LabelEncoder()

df['Actor 3'] = director_encoder.fit_transform(
    df['Actor 3']
)
df['Actor 3']

1         377
3        2572
5        2449
6        3030
8        1205
         ...
15501     868
15503    2014
15504    2725
15505     371
15508     355
Name: Actor 3, Length: 7919, dtype: int64

In [20]:
# data types
df.info()

<class 'pandas.DataFrame'>
Index: 7919 entries, 1 to 15508
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      7919 non-null   int64
 1   Duration  7919 non-null   float64
 2   Genre     7919 non-null   int64
 3   Rating    7919 non-null   float64
 4   Votes     7919 non-null   int64
 5   Director  7919 non-null   int64
 6   Actor 1   7919 non-null   int64
 7   Actor 2   7919 non-null   int64
 8   Actor 3   7919 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 618.7 KB

In [21]:
# saving
df.to_csv("../dataset/processed/cleaned_movies.csv", index = False)
print("Preprocessed dataset saved successful!!")

Preprocessed dataset saved successful!!

In [22]:
df.head()

   Year  Duration  Genre  Rating  Votes  Director  Actor 1  Actor 2  Actor 3
1  2019     109.0    268     7.0      8       811     1782     2815      377
3  2019     110.0    207     4.4     35      1749     1589      890     2572
5  1997     147.0    177     4.7    827      2005      508       85     2449
6  2005     142.0    331     7.4   1086      2643      931     1388     3030
8  2012      82.0    367     5.6    326       174     2521     1461     1205

In [23]:
# saving encoders
import joblib
joblib.dump(genre_encoder, "../models/genre_encoder.pkl")
joblib.dump(director_encoder, "../models/director_encoder.pkl")
joblib.dump(actor1_encoder, "../models/actor1_encoder.pkl")
joblib.dump(actor2_encoder, "../models/actor2_encoder.pkl")
joblib.dump(actor3_encoder, "../models/actor3_encoder.pkl")

['../models/actor3_encoder.pkl']